"""create game and score tables

First table-creating migration: autogenerated against the empty baseline from
the task 2.3 ORM models (``src/adapters/db/models.py``), then reviewed.

Creates the run aggregate (``dungeons`` -> ``floors`` -> ``enemies``, plus the
1:1 ``players`` table) with ON DELETE CASCADE foreign keys, and the standalone
``scores`` leaderboard table. ``scores.dungeon_id`` is intentionally NOT a
foreign key — scores outlive their runs. The ``ix_scores_value_computed_at``
index backs the leaderboard ordering (value DESC, computed_at ASC). Constraint
and index names come from the naming convention on ``Base.metadata``.

Revision ID: cb4012b33ce0
Revises: ffa16bba8245
Create Date: 2026-06-08 14:41:13.468845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb4012b33ce0'
down_revision: Union[str, Sequence[str], None] = 'ffa16bba8245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dungeons',
    sa.Column('dungeon_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('current_floor_index', sa.Integer(), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('dungeon_id', name=op.f('pk_dungeons'))
    )
    op.create_index(op.f('ix_dungeons_user_id'), 'dungeons', ['user_id'], unique=False)
    op.create_table('scores',
    sa.Column('score_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('dungeon_id', sa.Uuid(), nullable=False),
    sa.Column('floors_reached', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('item_multiplier', sa.Float(), nullable=False),
    sa.Column('damage_taken', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('score_id', name=op.f('pk_scores'))
    )
    op.create_index(op.f('ix_scores_user_id'), 'scores', ['user_id'], unique=False)
    op.create_index('ix_scores_value_computed_at', 'scores', [sa.literal_column('value DESC'), sa.literal_column('computed_at ASC')], unique=False)
    op.create_table('floors',
    sa.Column('floor_id', sa.Uuid(), nullable=False),
    sa.Column('dungeon_id', sa.Uuid(), nullable=False),
    sa.Column('floor_index', sa.Integer(), nullable=False),
    sa.Column('tiles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stairs_x', sa.Integer(), nullable=False),
    sa.Column('stairs_y', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dungeon_id'], ['dungeons.dungeon_id'], name=op.f('fk_floors_dungeon_id_dungeons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('floor_id', name=op.f('pk_floors')),
    sa.UniqueConstraint('dungeon_id', 'floor_index', name=op.f('uq_floors_dungeon_id'))
    )
    op.create_index(op.f('ix_floors_dungeon_id'), 'floors', ['dungeon_id'], unique=False)
    op.create_table('players',
    sa.Column('dungeon_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('damage_taken', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dungeon_id'], ['dungeons.dungeon_id'], name=op.f('fk_players_dungeon_id_dungeons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dungeon_id', name=op.f('pk_players'))
    )
    op.create_table('enemies',
    sa.Column('enemy_id', sa.Uuid(), nullable=False),
    sa.Column('floor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('behaviour', sa.Enum('MELEE', 'RANGED', 'BOSS', name='behaviourtype', native_enum=False), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('awake', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.floor_id'], name=op.f('fk_enemies_floor_id_floors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enemy_id', name=op.f('pk_enemies'))
    )
    op.create_index(op.f('ix_enemies_floor_id'), 'enemies', ['floor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enemies_floor_id'), table_name='enemies')
    op.drop_table('enemies')
    op.drop_table('players')
    op.drop_index(op.f('ix_floors_dungeon_id'), table_name='floors')
    op.drop_table('floors')
    op.drop_index('ix_scores_value_computed_at', table_name='scores')
    op.drop_index(op.f('ix_scores_user_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_dungeons_user_id'), table_name='dungeons')
    op.drop_table('dungeons')
    # ### end Alembic commands ###
