"""create weekly leaderboard archive

Adds the ``weekly_leaderboard_archive`` table behind task 4.4's
``weekly_leaderboard_reset`` job. The weekly leaderboard is a ``computed_at``
window over the shared ``scores`` table, so it resets itself when the week
advances; this table preserves a finished week's final standings, which would
otherwise be unrecoverable once the window moves.

One row per ranked entry. ``score_id`` is a plain column (no FK to ``scores``) —
an archive is immutable history that must outlive score / run cleanup. The
``uq_weekly_leaderboard_archive_week_start`` (week_start, score_id) unique
constraint backs the adapter's idempotent delete-then-insert per week.

Hand-authored (not autogenerated — that needs a live DB); chains linearly off
the previous head so the history stays single-headed (``test_migrations.py``).

Revision ID: f80ddbda61f8
Revises: cb4012b33ce0
Create Date: 2026-06-25 11:45:36.819996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80ddbda61f8'
down_revision: Union[str, Sequence[str], None] = 'cb4012b33ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'weekly_leaderboard_archive',
        sa.Column('archive_id', sa.Uuid(), nullable=False),
        sa.Column('week_start', sa.DateTime(timezone=True), nullable=False),
        sa.Column('rank', sa.Integer(), nullable=False),
        sa.Column('score_id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('value', sa.Integer(), nullable=False),
        sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('archive_id', name=op.f('pk_weekly_leaderboard_archive')),
        sa.UniqueConstraint(
            'week_start', 'score_id', name=op.f('uq_weekly_leaderboard_archive_week_start')
        ),
    )
    op.create_index(
        op.f('ix_weekly_leaderboard_archive_week_start'),
        'weekly_leaderboard_archive',
        ['week_start'],
        unique=False,
    )
    op.create_index(
        op.f('ix_weekly_leaderboard_archive_user_id'),
        'weekly_leaderboard_archive',
        ['user_id'],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        op.f('ix_weekly_leaderboard_archive_user_id'),
        table_name='weekly_leaderboard_archive',
    )
    op.drop_index(
        op.f('ix_weekly_leaderboard_archive_week_start'),
        table_name='weekly_leaderboard_archive',
    )
    op.drop_table('weekly_leaderboard_archive')
