"""initial baseline

Empty on purpose: this is the root of the migration history (down_revision is
None). No ORM models exist yet (task 2.3) so there is nothing to create. The
first table-creating migration will be autogenerated against this baseline once
the ORM models land. `upgrade`/`downgrade` are no-ops so the chain is reversible
all the way back to an empty database.

Revision ID: ffa16bba8245
Revises:
Create Date: 2026-06-02 14:32:57.614691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa16bba8245'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
